### Login
POST https://{{ authUrl}}/oauth/authorize
Authorization: Basic {{ basic }}

### Get profile
GET https://{{ baseUrl }}/profile
Authorization: Bearer {{ token }}

### Create profile
POST https://{{ baseUrl }}/profile
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "displayName": "Timo Benkhard"
}

### Create administration
POST https://{{ baseUrl }}/administration
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "name": "The new world"
}

### List administrations
GET https://{{ baseUrl }}/administration
Authorization: Bearer {{ token }}
Content-Type: application/json

### Invite tcbenkhard from tcbenkhard2
POST https://{{ baseUrl }}/invitation
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "user": "tcbenkhard@gmail.com",
  "administration": "4e509126-3fce-4b1b-8a08-0d389e3faba3",
  "role": "EDITOR"
}