### Login
POST https://{{ authUrl}}/oauth/authorize
Authorization: Basic {{ basic }}

### Get profile
GET https://{{ baseUrl }}/profile
Authorization: Bearer {{ token }}

### Create profile
POST https://{{ baseUrl }}/profile
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "displayName": "Timo Benkhard 2"
}

### Create administration
POST https://{{ baseUrl }}/administration
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "name": "The new world"
}

### List administrations
GET https://{{ baseUrl }}/administration
Authorization: Bearer {{ token }}
Content-Type: application/json

### Invite tcbenkhard from tcbenkhard2
POST https://{{ baseUrl }}/invitation
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "user": "tcbenkhard@gmail.com",
  "administration": "8c921b07-6754-4158-8200-17852692d3b1",
  "role": "EDITOR"
}

### Accept invitation as tcbenkhard
POST https://{{ baseUrl }}/invitation/8c921b07-6754-4158-8200-17852692d3b1/accept
Authorization: Bearer {{ token }}
Content-Type: application/json

{}

### Create group
POST https://{{ baseUrl }}/administration/8c921b07-6754-4158-8200-17852692d3b1/groups
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "name": "Inkomen",
  "description": "All salaries and benefits",
  "type": "INCOME"
}