### Login
POST https://{{ authUrl}}/oauth/authorize
Authorization: Basic dGNiZW5raGFyZEBnbWFpbC5jb206MTIzNDU2Nzg=

### Get profile
GET https://{{ baseUrl }}/profile
Authorization: Bearer {{ token }}

### Create profile
POST https://{{ baseUrl }}/profile
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "displayName": "Timo Benkhard"
}